In [63]:
import polars as pl

In [64]:
path = r"C:\Users\Rudra\Desktop\rural-financial-inclusion-govt-scheme-recommendation\parquet-data\lev-02\data\lev-02_merged.parquet"

df = pl.read_parquet(path)

In [65]:
df.shape

(1107221, 36)

In [66]:
df = df.filter(pl.col("State") == '10')

In [67]:
df.shape

(85751, 36)

In [68]:
import polars.selectors as cs

# Cast all currently string columns to Float, but only if they are numeric
df = df.with_columns(
    cs.string().cast(pl.Int32, strict=False)
)

In [69]:
df.schema

Schema([('Survey_Name', Int32),
        ('Year', Int32),
        ('FSU_Serial_No', Int32),
        ('Sector', Int32),
        ('State', Int32),
        ('NSS_Region', Int32),
        ('District', Int32),
        ('Stratum', Int32),
        ('Sub_stratum', Int32),
        ('Panel', Int32),
        ('Sub_sample', Int32),
        ('FOD_Sub_Region', Int32),
        ('Sample_SU_No', Int32),
        ('Sample_Sub_Division_No', Int32),
        ('Second_Stage_Stratum_No', Int32),
        ('Sample_Household_No', Int32),
        ('Questionnaire_No', Int32),
        ('Level', Int32),
        ('Person_Serial_No', Int32),
        ('Relation_to_Head', Int32),
        ('Gender', Int32),
        ('Age', Int32),
        ('Marital_Status', Int32),
        ('Education_Level', Int32),
        ('Years_of_Education', Int32),
        ('Used_Internet_Last_30_Days', Int32),
        ('Days_Away_From_Home_Last_30_Days', Int32),
        ('Meals_Usually_Taken_Per_Day', Int32),
        ('Meals_From_School', Int32),
        ('Meals_From_Employer', Int32),
        ('Meals_Other', Int32),
        ('Meals_On_Payment', Int32),
        ('Meals_At_Home', Int32),
        ('Revisit_Status', Int32),
        ('FDQ_Original_Member', Int32),
        ('Multiplier', Int64)])

In [70]:
df = df.filter(pl.col("State") == 10)

In [71]:
df

shape: (85_751, 36)
┌─────────────┬──────┬────────────┬────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ Survey_Name ┆ Year ┆ FSU_Serial ┆ Sector ┆ … ┆ Meals_At_H ┆ Revisit_St ┆ FDQ_Origin ┆ Multiplier │
│ ---         ┆ ---  ┆ _No        ┆ ---    ┆   ┆ ome        ┆ atus       ┆ al_Member  ┆ ---        │
│ i32         ┆ i32  ┆ ---        ┆ i32    ┆   ┆ ---        ┆ ---        ┆ ---        ┆ i64        │
│             ┆      ┆ i32        ┆        ┆   ┆ i32        ┆ i32        ┆ i32        ┆            │
╞═════════════╪══════╪════════════╪════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ null        ┆ 2024 ┆ 43528      ┆ 1      ┆ … ┆ 90         ┆ 1          ┆ 1          ┆ 114450     │
│ null        ┆ 2024 ┆ 43528      ┆ 1      ┆ … ┆ 90         ┆ 1          ┆ 1          ┆ 114450     │
│ null        ┆ 2024 ┆ 43528      ┆ 1      ┆ … ┆ 90         ┆ 1          ┆ 1          ┆ 114450     │
│ null        ┆ 2024 ┆ 43528      ┆ 1      ┆ … ┆ 90         ┆ 1          ┆ 1          ┆ 114450     │
│ null        ┆ 2024 ┆ 43528      ┆ 1      ┆ … ┆ 90         ┆ 1          ┆ 1          ┆ 114450     │
│ …           ┆ …    ┆ …          ┆ …      ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ null        ┆ 2024 ┆ 43277      ┆ 1      ┆ … ┆ 52         ┆ 1          ┆ 1          ┆ 157235     │
│ null        ┆ 2024 ┆ 43277      ┆ 1      ┆ … ┆ 90         ┆ 1          ┆ 1          ┆ 157235     │
│ null        ┆ 2024 ┆ 43277      ┆ 1      ┆ … ┆ 90         ┆ 1          ┆ 1          ┆ 157235     │
│ null        ┆ 2024 ┆ 43277      ┆ 1      ┆ … ┆ 60         ┆ 1          ┆ 1          ┆ 157235     │
│ null        ┆ 2024 ┆ 43277      ┆ 1      ┆ … ┆ 60         ┆ 1          ┆ 1          ┆ 157235     │
└─────────────┴──────┴────────────┴────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [72]:
df

shape: (85_751, 36)
┌─────────────┬──────┬────────────┬────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ Survey_Name ┆ Year ┆ FSU_Serial ┆ Sector ┆ … ┆ Meals_At_H ┆ Revisit_St ┆ FDQ_Origin ┆ Multiplier │
│ ---         ┆ ---  ┆ _No        ┆ ---    ┆   ┆ ome        ┆ atus       ┆ al_Member  ┆ ---        │
│ i32         ┆ i32  ┆ ---        ┆ i32    ┆   ┆ ---        ┆ ---        ┆ ---        ┆ i64        │
│             ┆      ┆ i32        ┆        ┆   ┆ i32        ┆ i32        ┆ i32        ┆            │
╞═════════════╪══════╪════════════╪════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ null        ┆ 2024 ┆ 43528      ┆ 1      ┆ … ┆ 90         ┆ 1          ┆ 1          ┆ 114450     │
│ null        ┆ 2024 ┆ 43528      ┆ 1      ┆ … ┆ 90         ┆ 1          ┆ 1          ┆ 114450     │
│ null        ┆ 2024 ┆ 43528      ┆ 1      ┆ … ┆ 90         ┆ 1          ┆ 1          ┆ 114450     │
│ null        ┆ 2024 ┆ 43528      ┆ 1      ┆ … ┆ 90         ┆ 1          ┆ 1          ┆ 114450     │
│ null        ┆ 2024 ┆ 43528      ┆ 1      ┆ … ┆ 90         ┆ 1          ┆ 1          ┆ 114450     │
│ …           ┆ …    ┆ …          ┆ …      ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ null        ┆ 2024 ┆ 43277      ┆ 1      ┆ … ┆ 52         ┆ 1          ┆ 1          ┆ 157235     │
│ null        ┆ 2024 ┆ 43277      ┆ 1      ┆ … ┆ 90         ┆ 1          ┆ 1          ┆ 157235     │
│ null        ┆ 2024 ┆ 43277      ┆ 1      ┆ … ┆ 90         ┆ 1          ┆ 1          ┆ 157235     │
│ null        ┆ 2024 ┆ 43277      ┆ 1      ┆ … ┆ 60         ┆ 1          ┆ 1          ┆ 157235     │
│ null        ┆ 2024 ┆ 43277      ┆ 1      ┆ … ┆ 60         ┆ 1          ┆ 1          ┆ 157235     │
└─────────────┴──────┴────────────┴────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [73]:
df.write_csv("test-bihar.csv")