In [2]:
import pandas as pd

In [ ]:
df1 = pd.read_csv(r"C:\Users\Rudra\Desktop\rural-financial-inclusion-govt-scheme-recommendation\bihar-datasets\BL01.csv")
df2 = pd.read_csv(r"C:\Users\Rudra\Desktop\rural-financial-inclusion-govt-scheme-recommendation\bihar-datasets\BL02.csv")
df3 = pd.read_csv(r"C:\Users\Rudra\Desktop\rural-financial-inclusion-govt-scheme-recommendation\bihar-datasets\BL02.csv")
df5 = pd.read_csv(r"C:\Users\Rudra\Desktop\rural-financial-inclusion-govt-scheme-recommendation\bihar-datasets\BL05.csv")
df9 = pd.read_csv(r"C:\Users\Rudra\Desktop\rural-financial-inclusion-govt-scheme-recommendation\bihar-datasets\BL09.csv")

# Columns

In [4]:
df1.columns

Index(['Survey_Name', 'Year', 'FSU_Serial_No', 'Sector', 'State', 'NSS_Region',
       'District', 'Stratum', 'Sub_stratum', 'Panel', 'Sub_sample',
       'FOD_Sub_Region', 'Sample_SU_No', 'Sample_Sub_Division_No',
       'Second_Stage_Stratum_No', 'Sample_Household_No', 'Questionnaire_No',
       'Level', 'Survey_Code', 'Reason_for_Substitution_Code', 'Multiplier',
       'Sector_label', 'State_label', 'Survey_Code_label',
       'Reason_for_Substitution_Code_label', 'ingest_timestamp',
       'ingest_date'],
      dtype='object')

In [5]:
df2.columns

Index(['Survey_Name', 'Year', 'FSU_Serial_No', 'Sector', 'State', 'NSS_Region',
       'District', 'Stratum', 'Sub_stratum', 'Panel', 'Sub_sample',
       'FOD_Sub_Region', 'Sample_SU_No', 'Sample_Sub_Division_No',
       'Second_Stage_Stratum_No', 'Sample_Household_No', 'Questionnaire_No',
       'Level', 'Person_Serial_No', 'Relation_to_Head', 'Gender', 'Age',
       'Marital_Status', 'Education_Level', 'Years_of_Education',
       'Used_Internet_Last_30_Days', 'Days_Away_From_Home_Last_30_Days',
       'Meals_Usually_Taken_Per_Day', 'Meals_From_School',
       'Meals_From_Employer', 'Meals_Other', 'Meals_On_Payment',
       'Meals_At_Home', 'Revisit_Status', 'FDQ_Original_Member', 'Multiplier',
       'Sector_label', 'State_label', 'Relation_to_Head_label', 'Gender_label',
       'Marital_Status_label', 'Education_Level_label',
       'Used_Internet_Last_30_Days_label', 'ingest_timestamp', 'ingest_date'],
      dtype='object')

In [6]:
df3.columns

Index(['Survey_Name', 'Year', 'FSU_Serial_No', 'Sector', 'State', 'NSS_Region',
       'District', 'Stratum', 'Sub_stratum', 'Panel', 'Sub_sample',
       'FOD_Sub_Region', 'Sample_SU_No', 'Sample_Sub_Division_No',
       'Second_Stage_Stratum_No', 'Sample_Household_No', 'Questionnaire_No',
       'Level', 'Person_Serial_No', 'Relation_to_Head', 'Gender', 'Age',
       'Marital_Status', 'Education_Level', 'Years_of_Education',
       'Used_Internet_Last_30_Days', 'Days_Away_From_Home_Last_30_Days',
       'Meals_Usually_Taken_Per_Day', 'Meals_From_School',
       'Meals_From_Employer', 'Meals_Other', 'Meals_On_Payment',
       'Meals_At_Home', 'Revisit_Status', 'FDQ_Original_Member', 'Multiplier',
       'Sector_label', 'State_label', 'Relation_to_Head_label', 'Gender_label',
       'Marital_Status_label', 'Education_Level_label',
       'Used_Internet_Last_30_Days_label', 'ingest_timestamp', 'ingest_date'],
      dtype='object')

In [26]:
df5.columns

Index(['Survey_Name', 'Year', 'FSU_Serial_No', 'Sector', 'State', 'NSS_Region',
       'District', 'Stratum', 'Sub_stratum', 'Panel', 'Sub_sample',
       'FOD_Sub_Region', 'Sample_SU_No', 'Sample_Sub_Division_No',
       'Second_Stage_Stratum_No', 'Sample_Household_No', 'Questionnaire_No',
       'Level', 'Item_Code', 'OutOfHome_Consumption_Quantity',
       'OutOfHome_Consumption_Value', 'Total_Consumption_Quantity',
       'Total_Consumption_Value', 'Source', 'Multiplier', 'Sector_label',
       'State_label', 'ingest_timestamp', 'ingest_date'],
      dtype='object')

In [27]:
df9.columns

Index(['Survey_Name', 'Year', 'FSU_Serial_No', 'Sector', 'State', 'NSS_Region',
       'District', 'Stratum', 'Sub_stratum', 'Panel', 'Sub_sample',
       'FOD_Sub_Region', 'Sample_SU_No', 'Sample_Sub_Division_No',
       'Second_Stage_Stratum_No', 'Sample_Household_No', 'Questionnaire_No',
       'Level', 'Item_Code_9_1_to_11_4', 'Value_Rs_9_1_to_11_4', 'Multiplier',
       'Sector_label', 'State_label', 'ingest_timestamp', 'ingest_date'],
      dtype='object')

# Filter

In [29]:
cols_01 = [
    'FSU_Serial_No', 'Sector',  'NSS_Region',
    'District', 'Stratum', 'Sub_stratum', 'Panel', 'Sub_sample',
    'FOD_Sub_Region', 'Sample_SU_No', 'Sample_Sub_Division_No',
    'Second_Stage_Stratum_No', 'Sample_Household_No', 'Questionnaire_No',
    'Level', 'Survey_Code', 'Reason_for_Substitution_Code', 
]

cols_02 = [
   'FSU_Serial_No', 'Sector', 'NSS_Region',
    'District', 'Stratum', 'Sub_stratum', 'Panel', 'Sub_sample',
    'FOD_Sub_Region', 'Sample_SU_No', 'Sample_Sub_Division_No',
    'Second_Stage_Stratum_No', 'Sample_Household_No', 'Questionnaire_No',
    'Level', 'Person_Serial_No',  
]

cols_03 = [
    'FSU_Serial_No', 'Sector', 'NSS_Region',
    'District', 'Stratum', 'Sub_stratum', 'Panel', 'Sub_sample',
    'FOD_Sub_Region', 'Sample_SU_No', 'Sample_Sub_Division_No',
    'Second_Stage_Stratum_No', 'Sample_Household_No', 'Questionnaire_No',
    'Level', 'Person_Serial_No', 
]

cols_05 = [
    'FSU_Serial_No', 'Sector', 'State', 'NSS_Region',
    'District', 'Stratum', 'Sub_stratum', 'Panel', 'Sub_sample',
    'FOD_Sub_Region', 'Sample_SU_No', 'Sample_Sub_Division_No',
    'Second_Stage_Stratum_No', 'Sample_Household_No', 'Questionnaire_No',
    'Level', 'Item_Code', 'OutOfHome_Consumption_Quantity',
    'OutOfHome_Consumption_Value', 'Total_Consumption_Quantity',
    'Total_Consumption_Value', 'Source'
]

cols_09 = [
    'FSU_Serial_No', 'Sector', 'State', 'NSS_Region',
    'District', 'Stratum', 'Sub_stratum', 'Panel', 'Sub_sample',
    'FOD_Sub_Region', 'Sample_SU_No', 'Sample_Sub_Division_No',
    'Second_Stage_Stratum_No', 'Sample_Household_No', 'Questionnaire_No',
    'Level', 'Item_Code_9_1_to_11_4', 'Value_Rs_9_1_to_11_4', 'Multiplier',
]

In [30]:
df1 = df1[cols_01]
df2 = df2[cols_02]
df3 = df3[cols_03]
df5 = df5[cols_05]
df9 = df9[cols_09]

# df1

In [9]:
df1.shape

(17255, 17)

In [10]:
for col in df1.columns:
    print(f"{col} -> {df1[col].nunique()}")

FSU_Serial_No -> 959
Sector -> 2
NSS_Region -> 2
District -> 38
Stratum -> 8
Sub_stratum -> 36
Panel -> 10
Sub_sample -> 2
FOD_Sub_Region -> 7
Sample_SU_No -> 27
Sample_Sub_Division_No -> 2
Second_Stage_Stratum_No -> 3
Sample_Household_No -> 18
Questionnaire_No -> 1
Level -> 1
Survey_Code -> 2
Reason_for_Substitution_Code -> 1

In [11]:
df1.head()

,FSU_Serial_No,Sector,NSS_Region,District,Stratum,Sub_stratum,Panel,Sub_sample,FOD_Sub_Region,Sample_SU_No,Sample_Sub_Division_No,Second_Stage_Stratum_No,Sample_Household_No,Questionnaire_No,Level,Survey_Code,Reason_for_Substitution_Code
0,43423,1,101,19,23,27,6,2,1011,3,NaN,3,2,H,1,1,NaN
1,43423,1,101,19,23,27,6,2,1011,3,NaN,3,3,H,1,1,NaN
2,43423,1,101,19,23,27,6,2,1011,3,NaN,3,4,H,1,1,NaN
3,43423,1,101,19,23,27,6,2,1011,3,NaN,3,5,H,1,1,NaN
4,43423,1,101,19,23,27,6,2,1011,3,NaN,3,6,H,1,1,NaN

# df2

In [12]:
df2.shape

(85751, 16)

In [13]:
for col in df2.columns:
    print(f"{col} -> {df2[col].nunique()}")

FSU_Serial_No -> 959
Sector -> 2
NSS_Region -> 2
District -> 38
Stratum -> 8
Sub_stratum -> 36
Panel -> 10
Sub_sample -> 2
FOD_Sub_Region -> 7
Sample_SU_No -> 27
Sample_Sub_Division_No -> 2
Second_Stage_Stratum_No -> 3
Sample_Household_No -> 18
Questionnaire_No -> 1
Level -> 1
Person_Serial_No -> 23

# df3

In [14]:
df3.shape

(85751, 16)

In [15]:
for col in df3.columns:
    print(f"{col} -> {df3[col].nunique()}")

FSU_Serial_No -> 959
Sector -> 2
NSS_Region -> 2
District -> 38
Stratum -> 8
Sub_stratum -> 36
Panel -> 10
Sub_sample -> 2
FOD_Sub_Region -> 7
Sample_SU_No -> 27
Sample_Sub_Division_No -> 2
Second_Stage_Stratum_No -> 3
Sample_Household_No -> 18
Questionnaire_No -> 1
Level -> 1
Person_Serial_No -> 23

# df5

In [33]:
df5.shape

(841515, 22)

In [31]:
for col in df5.columns:
    print(f"{col} -> {df5[col].nunique()}")

FSU_Serial_No -> 959
Sector -> 2
State -> 1
NSS_Region -> 2
District -> 38
Stratum -> 8
Sub_stratum -> 36
Panel -> 10
Sub_sample -> 2
FOD_Sub_Region -> 7
Sample_SU_No -> 27
Sample_Sub_Division_No -> 2
Second_Stage_Stratum_No -> 3
Sample_Household_No -> 18
Questionnaire_No -> 1
Level -> 1
Item_Code -> 136
OutOfHome_Consumption_Quantity -> 231
OutOfHome_Consumption_Value -> 1133
Total_Consumption_Quantity -> 3095
Total_Consumption_Value -> 2902
Source -> 7

# df9

In [34]:
df9.shape

(630, 19)

In [32]:
for col in df9.columns:
    print(f"{col} -> {df9[col].nunique()}")

FSU_Serial_No -> 1
Sector -> 1
State -> 1
NSS_Region -> 1
District -> 1
Stratum -> 1
Sub_stratum -> 1
Panel -> 1
Sub_sample -> 1
FOD_Sub_Region -> 1
Sample_SU_No -> 1
Sample_Sub_Division_No -> 0
Second_Stage_Stratum_No -> 1
Sample_Household_No -> 18
Questionnaire_No -> 1
Level -> 1
Item_Code_9_1_to_11_4 -> 59
Value_Rs_9_1_to_11_4 -> 144
Multiplier -> 1

# All fsu no are the same

In [16]:
l1 = df1['FSU_Serial_No'].unique().tolist()
l1 = sorted(l1)

In [17]:
l2 = df2['FSU_Serial_No'].unique().tolist()
l2 = sorted(l2)

In [18]:
l3 = df3['FSU_Serial_No'].unique().tolist()
l3 = sorted(l3)

In [19]:
l1 == l2 == l3

True

# check the unique values

In [20]:
cols = [
'Sector', 'NSS_Region',
'District', 'Stratum', 'Sub_stratum', 'Panel', 'Sub_sample',
'FOD_Sub_Region', 'Sample_SU_No', 'Sample_Sub_Division_No',
'Second_Stage_Stratum_No', 'Sample_Household_No', 'Questionnaire_No',
'Level', 
]

In [21]:
for col in cols:
    print(f"{col}\n{df1[col].unique()} \n {'-'*50}")

Sector
[1 2]
 --------------------------------------------------
NSS_Region
[101 102]
 --------------------------------------------------
District
[19  5 13 20  1 16 15  2 21 11  7 10  9 12  6  8 30 27 31 29 32 28 24 26
 23 36 22 25 37 35 34 33 38 14 18  4 17  3]
 --------------------------------------------------
Stratum
[23 13 22 21 12 32 42 41]
 --------------------------------------------------
Sub_stratum
[27 28 29 30 31 32 33 34 35 36  1  2  3  4  5  6  7  8  9 10 11 12 13 14
 15 16 17 18 19 20 21 22 23 24 25 26]
 --------------------------------------------------
Panel
[ 6  9 10  8  4  5  7  1  2  3]
 --------------------------------------------------
Sub_sample
[2 1]
 --------------------------------------------------
FOD_Sub_Region
[1011 1012 1013 1020 1021 1022 1010]
 --------------------------------------------------
Sample_SU_No
[ 3  8  1  2  7  9 10  4  6 12 11 13 17 22 16 15 31  5 20 21 34 14 18 23
 26 19 32]
 --------------------------------------------------
Sample_Sub_Division_No
[nan  2.  1.]
 --------------------------------------------------
Second_Stage_Stratum_No
[3 2 1]
 --------------------------------------------------
Sample_Household_No
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18  1]
 --------------------------------------------------
Questionnaire_No
['H']
 --------------------------------------------------
Level
[1]
 --------------------------------------------------

In [22]:
for col in cols:
    print(f"{col}\n{df2[col].unique()} \n {'-'*50}")
    
print(f"Person_Serial_No' -> {df2['Person_Serial_No'].unique()}")

Sector
[1 2]
 --------------------------------------------------
NSS_Region
[102 101]
 --------------------------------------------------
District
[28 33 16  7  5 12 17 14 18  4 20 19 13  1  2 21  9 10  6  8 15 11 31  3
 30 27 29 32 23 25 26 35 34 37 38 24 22 36]
 --------------------------------------------------
Stratum
[23 13 21 22 12 32 42 41]
 --------------------------------------------------
Sub_stratum
[32 25  1 26 35 15  2  3 10 11 13 17 18 20 22 23 30 31 33 34 36  6  7 14
 21 24 27 28 29  8  9 16 19  5  4 12]
 --------------------------------------------------
Panel
[ 1 10  2  6  3  4  5  7  8  9]
 --------------------------------------------------
Sub_sample
[2 1]
 --------------------------------------------------
FOD_Sub_Region
[1020 1022 1012 1013 1011 1010 1021]
 --------------------------------------------------
Sample_SU_No
[ 8  3  1 10  4  2  6 14 21 31  5  7 15 18 11 19  9 13 22 20 12 16 23 26
 32 17 34]
 --------------------------------------------------
Sample_Sub_Division_No
[nan  2.  1.]
 --------------------------------------------------
Second_Stage_Stratum_No
[3 1 2]
 --------------------------------------------------
Sample_Household_No
[15 14  8 12  9  5  1  2  3  4  6  7 10 11 13 16 17 18]
 --------------------------------------------------
Questionnaire_No
['H']
 --------------------------------------------------
Level
[2]
 --------------------------------------------------
Person_Serial_No' -> [ 5  6  7  8  2  3  4  1  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

In [23]:
for col in cols:
    print(f"{col}\n{df3[col].unique()} \n {'-'*50}")
    
print(f"Person_Serial_No' -> {df2['Person_Serial_No'].unique()}")

Sector
[1 2]
 --------------------------------------------------
NSS_Region
[102 101]
 --------------------------------------------------
District
[28 33 16  7  5 12 17 14 18  4 20 19 13  1  2 21  9 10  6  8 15 11 31  3
 30 27 29 32 23 25 26 35 34 37 38 24 22 36]
 --------------------------------------------------
Stratum
[23 13 21 22 12 32 42 41]
 --------------------------------------------------
Sub_stratum
[32 25  1 26 35 15  2  3 10 11 13 17 18 20 22 23 30 31 33 34 36  6  7 14
 21 24 27 28 29  8  9 16 19  5  4 12]
 --------------------------------------------------
Panel
[ 1 10  2  6  3  4  5  7  8  9]
 --------------------------------------------------
Sub_sample
[2 1]
 --------------------------------------------------
FOD_Sub_Region
[1020 1022 1012 1013 1011 1010 1021]
 --------------------------------------------------
Sample_SU_No
[ 8  3  1 10  4  2  6 14 21 31  5  7 15 18 11 19  9 13 22 20 12 16 23 26
 32 17 34]
 --------------------------------------------------
Sample_Sub_Division_No
[nan  2.  1.]
 --------------------------------------------------
Second_Stage_Stratum_No
[3 1 2]
 --------------------------------------------------
Sample_Household_No
[15 14  8 12  9  5  1  2  3  4  6  7 10 11 13 16 17 18]
 --------------------------------------------------
Questionnaire_No
['H']
 --------------------------------------------------
Level
[2]
 --------------------------------------------------
Person_Serial_No' -> [ 5  6  7  8  2  3  4  1  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

In [24]:
for col in cols:
    print(f"{col}\n{df3[col].unique()}")
    print( sorted(df2[col].unique().tolist()) == sorted(df3[col].unique().tolist()))

Sector
[1 2]
True
NSS_Region
[102 101]
True
District
[28 33 16  7  5 12 17 14 18  4 20 19 13  1  2 21  9 10  6  8 15 11 31  3
 30 27 29 32 23 25 26 35 34 37 38 24 22 36]
True
Stratum
[23 13 21 22 12 32 42 41]
True
Sub_stratum
[32 25  1 26 35 15  2  3 10 11 13 17 18 20 22 23 30 31 33 34 36  6  7 14
 21 24 27 28 29  8  9 16 19  5  4 12]
True

Panel
[ 1 10  2  6  3  4  5  7  8  9]
True
Sub_sample
[2 1]
True
FOD_Sub_Region
[1020 1022 1012 1013 1011 1010 1021]
True
Sample_SU_No
[ 8  3  1 10  4  2  6 14 21 31  5  7 15 18 11 19  9 13 22 20 12 16 23 26
 32 17 34]
True
Sample_Sub_Division_No
[nan  2.  1.]
False
Second_Stage_Stratum_No
[3 1 2]
True
Sample_Household_No
[15 14  8 12  9  5  1  2  3  4  6  7 10 11 13 16 17 18]
True
Questionnaire_No
['H']
True
Level
[2]
True

# df1 2700

In [36]:
df1[df1['FSU_Serial_No'] == 27000]

,FSU_Serial_No,Sector,NSS_Region,District,Stratum,Sub_stratum,Panel,Sub_sample,FOD_Sub_Region,Sample_SU_No,Sample_Sub_Division_No,Second_Stage_Stratum_No,Sample_Household_No,Questionnaire_No,Level,Survey_Code,Reason_for_Substitution_Code
13387,27000,2,102,37,22,3,1,1,1022,1,NaN,3,1,H,1,1,NaN
13388,27000,2,102,37,22,3,1,1,1022,1,NaN,3,2,H,1,1,NaN
13389,27000,2,102,37,22,3,1,1,1022,1,NaN,3,3,H,1,1,NaN
13390,27000,2,102,37,22,3,1,1,1022,1,NaN,3,4,H,1,1,NaN
13391,27000,2,102,37,22,3,1,1,1022,1,NaN,3,5,H,1,1,NaN
13392,27000,2,102,37,22,3,1,1,1022,1,NaN,3,6,H,1,1,NaN
13393,27000,2,102,37,22,3,1,1,1022,1,NaN,3,7,H,1,1,NaN
13394,27000,2,102,37,22,3,1,1,1022,1,NaN,3,8,H,1,1,NaN
13395,27000,2,102,37,22,3,1,1,1022,1,NaN,3,9,H,1,1,NaN
13396,27000,2,102,37,22,3,1,1,1022,1,NaN,3,10,H,1,1,NaN
13397,27000,2,102,37,22,3,1,1,1022,1,NaN,3,11,H,1,1,NaN
13398,27000,2,102,37,22,3,1,1,1022,1,NaN,3,12,H,1,1,NaN
13399,27000,2,102,37,22,3,1,1,1022,1,NaN,3,13,H,1,1,NaN
13400,27000,2,102,37,22,3,1,1,1022,1,NaN,3,14,H,1,1,NaN
13401,27000,2,102,37,22,3,1,1,1022,1,NaN,3,15,H,1,1,NaN
13402,27000,2,102,37,22,3,1,1,1022,1,NaN,3,16,H,1,1,NaN
13403,27000,2,102,37,22,3,1,1,1022,1,NaN,3,17,H,1,1,NaN
13404,27000,2,102,37,22,3,1,1,1022,1,NaN,3,18,H,1,1,NaN