In [81]:
category_mapping = {
    129: "cereals",
    139: "cereal substitute",
    159: "pulses & products",
    179: "salt & sugar",
    169: "milk & milk products",
    219: "vegetables",
    239: "fruits (fresh)",
    249: "fruits (dry)",
    199: "egg, fish & meat",
    189: "edible oil",
    269: "spices",
    279: "beverages",
    289: "served processed food",
    299: "packaged processed food"
}

In [82]:
category_mapping.items()

dict_items([(129, 'cereals'), (139, 'cereal substitute'), (159, 'pulses & products'), (179, 'salt & sugar'), (169, 'milk & milk products'), (219, 'vegetables'), (239, 'fruits (fresh)'), (249, 'fruits (dry)'), (199, 'egg, fish & meat'), (189, 'edible oil'), (269, 'spices'), (279, 'beverages'), (289, 'served processed food'), (299, 'packaged processed food')])

In [83]:
cereal_mapping = {
    61: "rice-free",
    62: "wheat/atta-free",
    70: "coarse grains-free",
    101: "rice – PDS",
    102: "rice – other sources",
    103: "chira",
    105: "muri",
    106: "other rice products (khoi/lawa, etc.)",
    107: "wheat/atta – PDS",
    108: "wheat/atta – other sources",
    110: "maida",
    111: "suji/rawa",
    112: "vermicelli (sewai)",
    114: "other wheat products",
    1: "coarse grains – PDS",
    2: "coarse grains – other sources",
    122: "other cereals & products",
    129: "cereals: sub-total"
}

In [84]:
data_dict = {**category_mapping, **cereal_mapping}

In [85]:
for key in data_dict:
    value = data_dict[key]
    print(f"({key}, '{value}'),")

(129, 'cereals: sub-total'),
(139, 'cereal substitute'),
(159, 'pulses & products'),
(179, 'salt & sugar'),
(169, 'milk & milk products'),
(219, 'vegetables'),
(239, 'fruits (fresh)'),
(249, 'fruits (dry)'),
(199, 'egg, fish & meat'),
(189, 'edible oil'),
(269, 'spices'),
(279, 'beverages'),
(289, 'served processed food'),
(299, 'packaged processed food'),
(61, 'rice-free'),
(62, 'wheat/atta-free'),
(70, 'coarse grains-free'),
(101, 'rice – PDS'),
(102, 'rice – other sources'),
(103, 'chira'),
(105, 'muri'),
(106, 'other rice products (khoi/lawa, etc.)'),
(107, 'wheat/atta – PDS'),
(108, 'wheat/atta – other sources'),
(110, 'maida'),
(111, 'suji/rawa'),
(112, 'vermicelli (sewai)'),
(114, 'other wheat products'),
(1, 'coarse grains – PDS'),
(2, 'coarse grains – other sources'),
(122, 'other cereals & products'),

In [86]:
for key in data_dict:
    value = data_dict[key]
    print(f"{key},{value}")

129,cereals: sub-total
139,cereal substitute
159,pulses & products
179,salt & sugar
169,milk & milk products
219,vegetables
239,fruits (fresh)
249,fruits (dry)
199,egg, fish & meat
189,edible oil
269,spices
279,beverages
289,served processed food
299,packaged processed food
61,rice-free
62,wheat/atta-free
70,coarse grains-free
101,rice – PDS
102,rice – other sources
103,chira
105,muri
106,other rice products (khoi/lawa, etc.)
107,wheat/atta – PDS
108,wheat/atta – other sources
110,maida
111,suji/rawa
112,vermicelli (sewai)
114,other wheat products
1,coarse grains – PDS
2,coarse grains – other sources
122,other cereals & products

In [87]:
import pandas as pd

In [88]:
df = pd.DataFrame()

In [89]:
df.from_dict(data_dict, orient="index", columns=["category"])

                                  category
129                     cereals: sub-total
139                      cereal substitute
159                      pulses & products
179                           salt & sugar
169                   milk & milk products
219                             vegetables
239                         fruits (fresh)
249                           fruits (dry)
199                       egg, fish & meat
189                             edible oil
269                                 spices
279                              beverages
289                  served processed food
299                packaged processed food
61                               rice-free
62                         wheat/atta-free
70                      coarse grains-free
101                             rice – PDS
102                   rice – other sources
103                                  chira
105                                   muri
106  other rice products (khoi/lawa, etc.)
107                       wheat/atta – PDS
108             wheat/atta – other sources
110                                  maida
111                              suji/rawa
112                     vermicelli (sewai)
114                   other wheat products
1                      coarse grains – PDS
2            coarse grains – other sources
122               other cereals & products

In [90]:
df = df.from_dict(data_dict, orient="index")

In [91]:
df = pd.DataFrame.from_dict(data_dict, orient="index").reset_index()
df.columns = ["item_code", "category"]

In [92]:
df

    item_code                               category
0         129                     cereals: sub-total
1         139                      cereal substitute
2         159                      pulses & products
3         179                           salt & sugar
4         169                   milk & milk products
5         219                             vegetables
6         239                         fruits (fresh)
7         249                           fruits (dry)
8         199                       egg, fish & meat
9         189                             edible oil
10        269                                 spices
11        279                              beverages
12        289                  served processed food
13        299                packaged processed food
14         61                              rice-free
15         62                        wheat/atta-free
16         70                     coarse grains-free
17        101                             rice – PDS
18        102                   rice – other sources
19        103                                  chira
20        105                                   muri
21        106  other rice products (khoi/lawa, etc.)
22        107                       wheat/atta – PDS
23        108             wheat/atta – other sources
24        110                                  maida
25        111                              suji/rawa
26        112                     vermicelli (sewai)
27        114                   other wheat products
28          1                    coarse grains – PDS
29          2          coarse grains – other sources
30        122               other cereals & products

In [93]:
df.to_csv("test-cat.csv", index=False)