# Goal: statistical-summary

In [1]:
""" 
Goal: statistical-summary
Author: Rudra Prasad Bhuyan
"""

' \nGoal: statistical-summary\nAuthor: Rudra Prasad Bhuyan\n'

In [2]:
import polars as pl

In [3]:
path = r"C:\Users\Rudra\Desktop\rural-financial-inclusion-govt-scheme-recommendation\parquet-data\lev-11\data\lev-11_merged.parquet"
pdf = pl.scan_parquet(path)

In [4]:
pdf.collect_schema()

Schema([('Survey_Name', String),
        ('Year', String),
        ('FSU_Serial_No', String),
        ('Sector', String),
        ('State', String),
        ('NSS_Region', String),
        ('District', String),
        ('Stratum', String),
        ('Sub_stratum', String),
        ('Panel', String),
        ('Sub_sample', String),
        ('FOD_Sub_Region', String),
        ('Sample_SU_No', String),
        ('Sample_Sub_Division_No', String),
        ('Second_Stage_Stratum_No', String),
        ('Sample_Household_No', String),
        ('questionnaire_No', String),
        ('Level', String),
        ('Online_Clothing', String),
        ('Online_Footwear', String),
        ('Online_Furniture', String),
        ('Online_Mobile', String),
        ('Online_PersonalGoods', String),
        ('Online_RecreationGoods', String),
        ('Online_HouseholdAppliances', String),
        ('Online_Crockery', String),
        ('Online_SportsGoods', String),
        ('Online_MedicalEquipment', String),
        ('Online_Bedding', String),
        ('Free_Laptop', String),
        ('Num_Free_Laptop', Float64),
        ('Free_Tablet', String),
        ('Num_Free_Tablet', Float64),
        ('Free_Mobile', String),
        ('Num_Free_Mobile', Float64),
        ('Free_Bicycle', String),
        ('Num_Free_Bicycle', Float64),
        ('Free_Scooter', String),
        ('Num_Free_Scooter', Float64),
        ('Free_Clothing', String),
        ('Num_Free_Clothing', Float64),
        ('Free_Footwear', String),
        ('Num_Free_Footwear', Float64),
        ('Free_Other', String),
        ('Num_Free_Other', Float64),
        ('Possess_Television', String),
        ('Possess_Radio', String),
        ('Possess_Laptop', String),
        ('Possess_Mobile', String),
        ('Possess_Bicycle', String),
        ('Possess_Scooter', String),
        ('Possess_Car', String),
        ('Possess_Truck', String),
        ('Possess_AnimalCart', String),
        ('Possess_Refrigerator', String),
        ('Possess_WashingMachine', String),
        ('Possess_AirCooler', String),
        ('TV_Facility_Type', String),
        ('Multiplier', Int64)])

# Useful Variables

In [5]:
online_cols = [
    'FSU_Serial_No',
'Online_Clothing',
'Online_Footwear',
'Online_Furniture',
'Online_Mobile',
'Online_PersonalGoods',
'Online_RecreationGoods',
'Online_HouseholdAppliances',
'Online_Crockery',
'Online_SportsGoods',
'Online_MedicalEquipment',
'Online_Bedding',
]

free_cols = [
'Free_Laptop',
'Num_Free_Laptop',
'Free_Tablet',
'Num_Free_Tablet',
'Free_Mobile',
'Num_Free_Mobile',
'Free_Bicycle',
'Num_Free_Bicycle',
'Free_Scooter',
'Num_Free_Scooter',
'Free_Clothing',
'Num_Free_Clothing',
'Free_Footwear',
'Num_Free_Footwear',
'Free_Other',
'Num_Free_Other',
]

possess_cols = [
'Possess_Television',
'Possess_Radio',
'Possess_Laptop',
'Possess_Mobile',
'Possess_Bicycle',
'Possess_Scooter',
'Possess_Car',
'Possess_Truck',
'Possess_AnimalCart',
'Possess_Refrigerator',
'Possess_WashingMachine',
'Possess_AirCooler',
'TV_Facility_Type',
]

cols = (
    online_cols 
    + free_cols
    + possess_cols
)

In [6]:
df = pdf.select(cols)

In [7]:
df.head(2).collect()

shape: (2, 41)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ FSU_Seria ┆ Online_Cl ┆ Online_Fo ┆ Online_Fu ┆ … ┆ Possess_R ┆ Possess_W ┆ Possess_A ┆ TV_Facil │
│ l_No      ┆ othing    ┆ otwear    ┆ rniture   ┆   ┆ efrigerat ┆ ashingMac ┆ irCooler  ┆ ity_Type │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ or        ┆ hine      ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ str       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆ str       ┆ str       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 46956     ┆ 1         ┆ 1         ┆           ┆ … ┆ 1         ┆           ┆           ┆ 3        │
│ 46956     ┆           ┆           ┆           ┆ … ┆ 1         ┆           ┆ 1         ┆ 3        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [8]:
df = df.with_columns(
    [pl.col(col).cast(pl.Int32, strict=False) for col in cols]
)

In [9]:
unique_counts = df.select(pl.all().n_unique()).collect()
unique_counts

shape: (1, 41)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ FSU_Seria ┆ Online_Cl ┆ Online_Fo ┆ Online_Fu ┆ … ┆ Possess_R ┆ Possess_W ┆ Possess_A ┆ TV_Facil │
│ l_No      ┆ othing    ┆ otwear    ┆ rniture   ┆   ┆ efrigerat ┆ ashingMac ┆ irCooler  ┆ ity_Type │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ or        ┆ hine      ┆ ---       ┆ ---      │
│ u32       ┆ u32       ┆ u32       ┆ u32       ┆   ┆ ---       ┆ ---       ┆ u32       ┆ u32      │
│           ┆           ┆           ┆           ┆   ┆ u32       ┆ u32       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 14827     ┆ 2         ┆ 2         ┆ 2         ┆ … ┆ 2         ┆ 2         ┆ 2         ┆ 4        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

# Logic

In [10]:
categorical_cols = []
numerical_cols = []

for col in df.columns:
    if unique_counts[col][0] <13:
        categorical_cols.append(col)
    else:
        numerical_cols.append(col)

C:\Users\Rudra\AppData\Local\Temp\ipykernel_13616\2508435801.py:4: PerformanceWarning: Determining the column names of a LazyFrame requires resolving its schema, which is a potentially expensive operation. Use `LazyFrame.collect_schema().names()` to get the column names without this warning.
  for col in df.columns:

# Numerical Columns

In [11]:
stats = df.select(numerical_cols).describe()
with pl.Config(tbl_rows=-1, tbl_cols=-1):
    display(stats.to_pandas().T)

,0,1,2,3,4,5,6,7,8
statistic,count,null_count,mean,std,min,25%,50%,75%,max
FSU_Serial_No,523906.0,0.0,37348.497543,9904.297639,22300.0,26451.0,42231.0,46160.0,49999.0
Num_Free_Clothing,42692.0,481214.0,2.731519,2.000589,1.0,2.0,2.0,4.0,29.0
Num_Free_Footwear,18198.0,505708.0,1.851522,1.12212,1.0,1.0,2.0,2.0,14.0
Num_Free_Other,12474.0,511432.0,4.367484,5.256535,1.0,2.0,2.0,6.0,56.0

# Categorical Columns

In [12]:
for col in categorical_cols:
    print(col)
    counts = df.select(pl.col(col).value_counts(sort=True)).collect()
    
    with pl.Config(tbl_rows=-1, tbl_cols=-1):
        display(counts.unnest(col))

Online_Clothing

shape: (2, 2)
┌─────────────────┬────────┐
│ Online_Clothing ┆ count  │
│ ---             ┆ ---    │
│ i32             ┆ u32    │
╞═════════════════╪════════╡
│ null            ┆ 401642 │
│ 1               ┆ 122264 │
└─────────────────┴────────┘

Online_Footwear

shape: (2, 2)
┌─────────────────┬────────┐
│ Online_Footwear ┆ count  │
│ ---             ┆ ---    │
│ i32             ┆ u32    │
╞═════════════════╪════════╡
│ null            ┆ 448600 │
│ 1               ┆ 75306  │
└─────────────────┴────────┘

Online_Furniture

shape: (2, 2)
┌──────────────────┬────────┐
│ Online_Furniture ┆ count  │
│ ---              ┆ ---    │
│ i32              ┆ u32    │
╞══════════════════╪════════╡
│ null             ┆ 522776 │
│ 1                ┆ 1130   │
└──────────────────┴────────┘

Online_Mobile

shape: (2, 2)
┌───────────────┬────────┐
│ Online_Mobile ┆ count  │
│ ---           ┆ ---    │
│ i32           ┆ u32    │
╞═══════════════╪════════╡
│ null          ┆ 516998 │
│ 1             ┆ 6908   │
└───────────────┴────────┘

Online_PersonalGoods

shape: (2, 2)
┌──────────────────────┬────────┐
│ Online_PersonalGoods ┆ count  │
│ ---                  ┆ ---    │
│ i32                  ┆ u32    │
╞══════════════════════╪════════╡
│ null                 ┆ 505366 │
│ 1                    ┆ 18540  │
└──────────────────────┴────────┘

Online_RecreationGoods

shape: (2, 2)
┌────────────────────────┬────────┐
│ Online_RecreationGoods ┆ count  │
│ ---                    ┆ ---    │
│ i32                    ┆ u32    │
╞════════════════════════╪════════╡
│ null                   ┆ 521048 │
│ 1                      ┆ 2858   │
└────────────────────────┴────────┘

Online_HouseholdAppliances

shape: (2, 2)
┌────────────────────────────┬────────┐
│ Online_HouseholdAppliances ┆ count  │
│ ---                        ┆ ---    │
│ i32                        ┆ u32    │
╞════════════════════════════╪════════╡
│ null                       ┆ 518224 │
│ 1                          ┆ 5682   │
└────────────────────────────┴────────┘

Online_Crockery

shape: (2, 2)
┌─────────────────┬────────┐
│ Online_Crockery ┆ count  │
│ ---             ┆ ---    │
│ i32             ┆ u32    │
╞═════════════════╪════════╡
│ null            ┆ 517530 │
│ 1               ┆ 6376   │
└─────────────────┴────────┘

Online_SportsGoods

shape: (2, 2)
┌────────────────────┬────────┐
│ Online_SportsGoods ┆ count  │
│ ---                ┆ ---    │
│ i32                ┆ u32    │
╞════════════════════╪════════╡
│ null               ┆ 518464 │
│ 1                  ┆ 5442   │
└────────────────────┴────────┘

Online_MedicalEquipment

shape: (2, 2)
┌─────────────────────────┬────────┐
│ Online_MedicalEquipment ┆ count  │
│ ---                     ┆ ---    │
│ i32                     ┆ u32    │
╞═════════════════════════╪════════╡
│ null                    ┆ 521966 │
│ 1                       ┆ 1940   │
└─────────────────────────┴────────┘

Online_Bedding

shape: (2, 2)
┌────────────────┬────────┐
│ Online_Bedding ┆ count  │
│ ---            ┆ ---    │
│ i32            ┆ u32    │
╞════════════════╪════════╡
│ null           ┆ 512358 │
│ 1              ┆ 11548  │
└────────────────┴────────┘

Free_Laptop

shape: (2, 2)
┌─────────────┬────────┐
│ Free_Laptop ┆ count  │
│ ---         ┆ ---    │
│ i32         ┆ u32    │
╞═════════════╪════════╡
│ null        ┆ 523736 │
│ 1           ┆ 170    │
└─────────────┴────────┘

Num_Free_Laptop

shape: (3, 2)
┌─────────────────┬────────┐
│ Num_Free_Laptop ┆ count  │
│ ---             ┆ ---    │
│ i32             ┆ u32    │
╞═════════════════╪════════╡
│ null            ┆ 523736 │
│ 1               ┆ 158    │
│ 2               ┆ 12     │
└─────────────────┴────────┘

Free_Tablet

shape: (2, 2)
┌─────────────┬────────┐
│ Free_Tablet ┆ count  │
│ ---         ┆ ---    │
│ i32         ┆ u32    │
╞═════════════╪════════╡
│ null        ┆ 523546 │
│ 1           ┆ 360    │
└─────────────┴────────┘

Num_Free_Tablet

shape: (3, 2)
┌─────────────────┬────────┐
│ Num_Free_Tablet ┆ count  │
│ ---             ┆ ---    │
│ i32             ┆ u32    │
╞═════════════════╪════════╡
│ null            ┆ 523546 │
│ 1               ┆ 344    │
│ 2               ┆ 16     │
└─────────────────┴────────┘

Free_Mobile

shape: (2, 2)
┌─────────────┬────────┐
│ Free_Mobile ┆ count  │
│ ---         ┆ ---    │
│ i32         ┆ u32    │
╞═════════════╪════════╡
│ null        ┆ 521930 │
│ 1           ┆ 1976   │
└─────────────┴────────┘

Num_Free_Mobile

shape: (4, 2)
┌─────────────────┬────────┐
│ Num_Free_Mobile ┆ count  │
│ ---             ┆ ---    │
│ i32             ┆ u32    │
╞═════════════════╪════════╡
│ null            ┆ 521930 │
│ 1               ┆ 1930   │
│ 2               ┆ 44     │
│ 3               ┆ 2      │
└─────────────────┴────────┘

Free_Bicycle

shape: (2, 2)
┌──────────────┬────────┐
│ Free_Bicycle ┆ count  │
│ ---          ┆ ---    │
│ i32          ┆ u32    │
╞══════════════╪════════╡
│ null         ┆ 521868 │
│ 1            ┆ 2038   │
└──────────────┴────────┘

Num_Free_Bicycle

shape: (3, 2)
┌──────────────────┬────────┐
│ Num_Free_Bicycle ┆ count  │
│ ---              ┆ ---    │
│ i32              ┆ u32    │
╞══════════════════╪════════╡
│ null             ┆ 521868 │
│ 1                ┆ 1944   │
│ 2                ┆ 94     │
└──────────────────┴────────┘

Free_Scooter

shape: (2, 2)
┌──────────────┬────────┐
│ Free_Scooter ┆ count  │
│ ---          ┆ ---    │
│ i32          ┆ u32    │
╞══════════════╪════════╡
│ null         ┆ 523818 │
│ 1            ┆ 88     │
└──────────────┴────────┘

Num_Free_Scooter

shape: (3, 2)
┌──────────────────┬────────┐
│ Num_Free_Scooter ┆ count  │
│ ---              ┆ ---    │
│ i32              ┆ u32    │
╞══════════════════╪════════╡
│ null             ┆ 523818 │
│ 1                ┆ 82     │
│ 2                ┆ 6      │
└──────────────────┴────────┘

Free_Clothing

shape: (2, 2)
┌───────────────┬────────┐
│ Free_Clothing ┆ count  │
│ ---           ┆ ---    │
│ i32           ┆ u32    │
╞═══════════════╪════════╡
│ null          ┆ 481214 │
│ 1             ┆ 42692  │
└───────────────┴────────┘

Free_Footwear

shape: (2, 2)
┌───────────────┬────────┐
│ Free_Footwear ┆ count  │
│ ---           ┆ ---    │
│ i32           ┆ u32    │
╞═══════════════╪════════╡
│ null          ┆ 505708 │
│ 1             ┆ 18198  │
└───────────────┴────────┘

Free_Other

shape: (2, 2)
┌────────────┬────────┐
│ Free_Other ┆ count  │
│ ---        ┆ ---    │
│ i32        ┆ u32    │
╞════════════╪════════╡
│ null       ┆ 511432 │
│ 1          ┆ 12474  │
└────────────┴────────┘

Possess_Television

shape: (2, 2)
┌────────────────────┬────────┐
│ Possess_Television ┆ count  │
│ ---                ┆ ---    │
│ i32                ┆ u32    │
╞════════════════════╪════════╡
│ 1                  ┆ 363810 │
│ null               ┆ 160096 │
└────────────────────┴────────┘

Possess_Radio

shape: (2, 2)
┌───────────────┬────────┐
│ Possess_Radio ┆ count  │
│ ---           ┆ ---    │
│ i32           ┆ u32    │
╞═══════════════╪════════╡
│ null          ┆ 513176 │
│ 1             ┆ 10730  │
└───────────────┴────────┘

Possess_Laptop

shape: (2, 2)
┌────────────────┬────────┐
│ Possess_Laptop ┆ count  │
│ ---            ┆ ---    │
│ i32            ┆ u32    │
╞════════════════╪════════╡
│ null           ┆ 482662 │
│ 1              ┆ 41244  │
└────────────────┴────────┘

Possess_Mobile

shape: (2, 2)
┌────────────────┬────────┐
│ Possess_Mobile ┆ count  │
│ ---            ┆ ---    │
│ i32            ┆ u32    │
╞════════════════╪════════╡
│ 1              ┆ 511068 │
│ null           ┆ 12838  │
└────────────────┴────────┘

Possess_Bicycle

shape: (2, 2)
┌─────────────────┬────────┐
│ Possess_Bicycle ┆ count  │
│ ---             ┆ ---    │
│ i32             ┆ u32    │
╞═════════════════╪════════╡
│ null            ┆ 320532 │
│ 1               ┆ 203374 │
└─────────────────┴────────┘

Possess_Scooter

shape: (2, 2)
┌─────────────────┬────────┐
│ Possess_Scooter ┆ count  │
│ ---             ┆ ---    │
│ i32             ┆ u32    │
╞═════════════════╪════════╡
│ 1               ┆ 316812 │
│ null            ┆ 207094 │
└─────────────────┴────────┘

Possess_Car

shape: (2, 2)
┌─────────────┬────────┐
│ Possess_Car ┆ count  │
│ ---         ┆ ---    │
│ i32         ┆ u32    │
╞═════════════╪════════╡
│ null        ┆ 479162 │
│ 1           ┆ 44744  │
└─────────────┴────────┘

Possess_Truck

shape: (2, 2)
┌───────────────┬────────┐
│ Possess_Truck ┆ count  │
│ ---           ┆ ---    │
│ i32           ┆ u32    │
╞═══════════════╪════════╡
│ null          ┆ 523436 │
│ 1             ┆ 470    │
└───────────────┴────────┘

Possess_AnimalCart

shape: (2, 2)
┌────────────────────┬────────┐
│ Possess_AnimalCart ┆ count  │
│ ---                ┆ ---    │
│ i32                ┆ u32    │
╞════════════════════╪════════╡
│ null               ┆ 520786 │
│ 1                  ┆ 3120   │
└────────────────────┴────────┘

Possess_Refrigerator

shape: (2, 2)
┌──────────────────────┬────────┐
│ Possess_Refrigerator ┆ count  │
│ ---                  ┆ ---    │
│ i32                  ┆ u32    │
╞══════════════════════╪════════╡
│ null                 ┆ 269788 │
│ 1                    ┆ 254118 │
└──────────────────────┴────────┘

Possess_WashingMachine

shape: (2, 2)
┌────────────────────────┬────────┐
│ Possess_WashingMachine ┆ count  │
│ ---                    ┆ ---    │
│ i32                    ┆ u32    │
╞════════════════════════╪════════╡
│ null                   ┆ 397836 │
│ 1                      ┆ 126070 │
└────────────────────────┴────────┘

Possess_AirCooler

shape: (2, 2)
┌───────────────────┬────────┐
│ Possess_AirCooler ┆ count  │
│ ---               ┆ ---    │
│ i32               ┆ u32    │
╞═══════════════════╪════════╡
│ null              ┆ 370198 │
│ 1                 ┆ 153708 │
└───────────────────┴────────┘

TV_Facility_Type

shape: (4, 2)
┌──────────────────┬────────┐
│ TV_Facility_Type ┆ count  │
│ ---              ┆ ---    │
│ i32              ┆ u32    │
╞══════════════════╪════════╡
│ 3                ┆ 191922 │
│ null             ┆ 160096 │
│ 2                ┆ 121494 │
│ 1                ┆ 50394  │
└──────────────────┴────────┘