In [35]:
path = r"C:\Users\Rudra\Desktop\rural-financial-inclusion-govt-scheme-recommendation\parquet-data\lev-11\data\lev-11_merged.parquet"

# import 
import pandas as pd
import polars as pl
import missingno as msgo
import matplotlib.pyplot as plt
import seaborn as sns

In [36]:
# Import Data and filter
pdf = pl.read_parquet(path)
display(f"Before Filtering the shape {pdf.shape}")
pdf = pdf.filter(
    pl.col('State') == '23'
)
display(f"After Filter the shape {pdf.shape}")

'Before Filtering the shape (523906, 59)'

'After Filter the shape (28210, 59)'

In [37]:
online_cols = [
    'FSU_Serial_No',
'Online_Clothing',
'Online_Footwear',
'Online_Furniture',
'Online_Mobile',
'Online_PersonalGoods',
'Online_RecreationGoods',
'Online_HouseholdAppliances',
'Online_Crockery',
'Online_SportsGoods',
'Online_MedicalEquipment',
'Online_Bedding',
]

free_cols = [
'Free_Laptop',
'Num_Free_Laptop',
'Free_Tablet',
'Num_Free_Tablet',
'Free_Mobile',
'Num_Free_Mobile',
'Free_Bicycle',
'Num_Free_Bicycle',
'Free_Scooter',
'Num_Free_Scooter',
'Free_Clothing',
'Num_Free_Clothing',
'Free_Footwear',
'Num_Free_Footwear',
'Free_Other',
'Num_Free_Other',
]

possess_cols = [
'Possess_Television',
'Possess_Radio',
'Possess_Laptop',
'Possess_Mobile',
'Possess_Bicycle',
'Possess_Scooter',
'Possess_Car',
'Possess_Truck',
'Possess_AnimalCart',
'Possess_Refrigerator',
'Possess_WashingMachine',
'Possess_AirCooler',
'TV_Facility_Type',
]

all_cols = (
    online_cols 
    + free_cols
    + possess_cols
)
pdf = pdf[all_cols]

display(f"Desire Filter shape {pdf.shape}")

'Desire Filter shape (28210, 41)'

In [38]:

# str -> int 
pdf = pdf.with_columns(
    [pl.col(col).cast(pl.Int16, strict=False) for col in pdf.columns]
)

display(pdf.schema)

Schema([('FSU_Serial_No', Int16),
        ('Online_Clothing', Int16),
        ('Online_Footwear', Int16),
        ('Online_Furniture', Int16),
        ('Online_Mobile', Int16),
        ('Online_PersonalGoods', Int16),
        ('Online_RecreationGoods', Int16),
        ('Online_HouseholdAppliances', Int16),
        ('Online_Crockery', Int16),
        ('Online_SportsGoods', Int16),
        ('Online_MedicalEquipment', Int16),
        ('Online_Bedding', Int16),
        ('Free_Laptop', Int16),
        ('Num_Free_Laptop', Int16),
        ('Free_Tablet', Int16),
        ('Num_Free_Tablet', Int16),
        ('Free_Mobile', Int16),
        ('Num_Free_Mobile', Int16),
        ('Free_Bicycle', Int16),
        ('Num_Free_Bicycle', Int16),
        ('Free_Scooter', Int16),
        ('Num_Free_Scooter', Int16),
        ('Free_Clothing', Int16),
        ('Num_Free_Clothing', Int16),
        ('Free_Footwear', Int16),
        ('Num_Free_Footwear', Int16),
        ('Free_Other', Int16),
        ('Num_Free_Other', Int16),
        ('Possess_Television', Int16),
        ('Possess_Radio', Int16),
        ('Possess_Laptop', Int16),
        ('Possess_Mobile', Int16),
        ('Possess_Bicycle', Int16),
        ('Possess_Scooter', Int16),
        ('Possess_Car', Int16),
        ('Possess_Truck', Int16),
        ('Possess_AnimalCart', Int16),
        ('Possess_Refrigerator', Int16),
        ('Possess_WashingMachine', Int16),
        ('Possess_AirCooler', Int16),
        ('TV_Facility_Type', Int16)])

# Online

In [39]:
pdf[online_cols].null_count()

shape: (1, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ FSU_Seria ┆ Online_Cl ┆ Online_Fo ┆ Online_Fu ┆ … ┆ Online_Cr ┆ Online_Sp ┆ Online_Me ┆ Online_B │
│ l_No      ┆ othing    ┆ otwear    ┆ rniture   ┆   ┆ ockery    ┆ ortsGoods ┆ dicalEqui ┆ edding   │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ pment     ┆ ---      │
│ u32       ┆ u32       ┆ u32       ┆ u32       ┆   ┆ u32       ┆ u32       ┆ ---       ┆ u32      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ u32       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 16852     ┆ 23808     ┆ 25176     ┆ 28196     ┆ … ┆ 28108     ┆ 28028     ┆ 28182     ┆ 27896    │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [40]:
for col in pdf[online_cols].columns:
    display(pdf[col].value_counts())

shape: (320, 2)
┌───────────────┬───────┐
│ FSU_Serial_No ┆ count │
│ ---           ┆ ---   │
│ i16           ┆ u32   │
╞═══════════════╪═══════╡
│ 25254         ┆ 36    │
│ 25803         ┆ 36    │
│ 25062         ┆ 36    │
│ 25167         ┆ 36    │
│ 25028         ┆ 34    │
│ …             ┆ …     │
│ 25005         ┆ 36    │
│ 25295         ┆ 36    │
│ 25248         ┆ 34    │
│ 25229         ┆ 34    │
│ 25046         ┆ 32    │
└───────────────┴───────┘

shape: (2, 2)
┌─────────────────┬───────┐
│ Online_Clothing ┆ count │
│ ---             ┆ ---   │
│ i16             ┆ u32   │
╞═════════════════╪═══════╡
│ 1               ┆ 4402  │
│ null            ┆ 23808 │
└─────────────────┴───────┘

shape: (2, 2)
┌─────────────────┬───────┐
│ Online_Footwear ┆ count │
│ ---             ┆ ---   │
│ i16             ┆ u32   │
╞═════════════════╪═══════╡
│ null            ┆ 25176 │
│ 1               ┆ 3034  │
└─────────────────┴───────┘

shape: (2, 2)
┌──────────────────┬───────┐
│ Online_Furniture ┆ count │
│ ---              ┆ ---   │
│ i16              ┆ u32   │
╞══════════════════╪═══════╡
│ 1                ┆ 14    │
│ null             ┆ 28196 │
└──────────────────┴───────┘

shape: (2, 2)
┌───────────────┬───────┐
│ Online_Mobile ┆ count │
│ ---           ┆ ---   │
│ i16           ┆ u32   │
╞═══════════════╪═══════╡
│ null          ┆ 27966 │
│ 1             ┆ 244   │
└───────────────┴───────┘

shape: (2, 2)
┌──────────────────────┬───────┐
│ Online_PersonalGoods ┆ count │
│ ---                  ┆ ---   │
│ i16                  ┆ u32   │
╞══════════════════════╪═══════╡
│ 1                    ┆ 622   │
│ null                 ┆ 27588 │
└──────────────────────┴───────┘

shape: (2, 2)
┌────────────────────────┬───────┐
│ Online_RecreationGoods ┆ count │
│ ---                    ┆ ---   │
│ i16                    ┆ u32   │
╞════════════════════════╪═══════╡
│ 1                      ┆ 72    │
│ null                   ┆ 28138 │
└────────────────────────┴───────┘

shape: (2, 2)
┌────────────────────────────┬───────┐
│ Online_HouseholdAppliances ┆ count │
│ ---                        ┆ ---   │
│ i16                        ┆ u32   │
╞════════════════════════════╪═══════╡
│ null                       ┆ 28140 │
│ 1                          ┆ 70    │
└────────────────────────────┴───────┘

shape: (2, 2)
┌─────────────────┬───────┐
│ Online_Crockery ┆ count │
│ ---             ┆ ---   │
│ i16             ┆ u32   │
╞═════════════════╪═══════╡
│ 1               ┆ 102   │
│ null            ┆ 28108 │
└─────────────────┴───────┘

shape: (2, 2)
┌────────────────────┬───────┐
│ Online_SportsGoods ┆ count │
│ ---                ┆ ---   │
│ i16                ┆ u32   │
╞════════════════════╪═══════╡
│ 1                  ┆ 182   │
│ null               ┆ 28028 │
└────────────────────┴───────┘

shape: (2, 2)
┌─────────────────────────┬───────┐
│ Online_MedicalEquipment ┆ count │
│ ---                     ┆ ---   │
│ i16                     ┆ u32   │
╞═════════════════════════╪═══════╡
│ null                    ┆ 28182 │
│ 1                       ┆ 28    │
└─────────────────────────┴───────┘

shape: (2, 2)
┌────────────────┬───────┐
│ Online_Bedding ┆ count │
│ ---            ┆ ---   │
│ i16            ┆ u32   │
╞════════════════╪═══════╡
│ null           ┆ 27896 │
│ 1              ┆ 314   │
└────────────────┴───────┘

In [41]:
for col in pdf[online_cols].columns:
    pdf = pdf.with_columns(
    pl.col(col).fill_null(strategy='zero')
)

# Free

In [42]:
for col in pdf[free_cols].columns:
    display(pdf[col].value_counts())

shape: (1, 2)
┌─────────────┬───────┐
│ Free_Laptop ┆ count │
│ ---         ┆ ---   │
│ i16         ┆ u32   │
╞═════════════╪═══════╡
│ null        ┆ 28210 │
└─────────────┴───────┘

shape: (1, 2)
┌─────────────────┬───────┐
│ Num_Free_Laptop ┆ count │
│ ---             ┆ ---   │
│ i16             ┆ u32   │
╞═════════════════╪═══════╡
│ null            ┆ 28210 │
└─────────────────┴───────┘

shape: (2, 2)
┌─────────────┬───────┐
│ Free_Tablet ┆ count │
│ ---         ┆ ---   │
│ i16         ┆ u32   │
╞═════════════╪═══════╡
│ 1           ┆ 4     │
│ null        ┆ 28206 │
└─────────────┴───────┘

shape: (2, 2)
┌─────────────────┬───────┐
│ Num_Free_Tablet ┆ count │
│ ---             ┆ ---   │
│ i16             ┆ u32   │
╞═════════════════╪═══════╡
│ 1               ┆ 4     │
│ null            ┆ 28206 │
└─────────────────┴───────┘

shape: (2, 2)
┌─────────────┬───────┐
│ Free_Mobile ┆ count │
│ ---         ┆ ---   │
│ i16         ┆ u32   │
╞═════════════╪═══════╡
│ null        ┆ 28208 │
│ 1           ┆ 2     │
└─────────────┴───────┘

shape: (2, 2)
┌─────────────────┬───────┐
│ Num_Free_Mobile ┆ count │
│ ---             ┆ ---   │
│ i16             ┆ u32   │
╞═════════════════╪═══════╡
│ 1               ┆ 2     │
│ null            ┆ 28208 │
└─────────────────┴───────┘

shape: (2, 2)
┌──────────────┬───────┐
│ Free_Bicycle ┆ count │
│ ---          ┆ ---   │
│ i16          ┆ u32   │
╞══════════════╪═══════╡
│ null         ┆ 28110 │
│ 1            ┆ 100   │
└──────────────┴───────┘

shape: (3, 2)
┌──────────────────┬───────┐
│ Num_Free_Bicycle ┆ count │
│ ---              ┆ ---   │
│ i16              ┆ u32   │
╞══════════════════╪═══════╡
│ 2                ┆ 10    │
│ null             ┆ 28110 │
│ 1                ┆ 90    │
└──────────────────┴───────┘

shape: (2, 2)
┌──────────────┬───────┐
│ Free_Scooter ┆ count │
│ ---          ┆ ---   │
│ i16          ┆ u32   │
╞══════════════╪═══════╡
│ null         ┆ 28206 │
│ 1            ┆ 4     │
└──────────────┴───────┘

shape: (2, 2)
┌──────────────────┬───────┐
│ Num_Free_Scooter ┆ count │
│ ---              ┆ ---   │
│ i16              ┆ u32   │
╞══════════════════╪═══════╡
│ null             ┆ 28206 │
│ 1                ┆ 4     │
└──────────────────┴───────┘

shape: (2, 2)
┌───────────────┬───────┐
│ Free_Clothing ┆ count │
│ ---           ┆ ---   │
│ i16           ┆ u32   │
╞═══════════════╪═══════╡
│ null          ┆ 26516 │
│ 1             ┆ 1694  │
└───────────────┴───────┘

shape: (13, 2)
┌───────────────────┬───────┐
│ Num_Free_Clothing ┆ count │
│ ---               ┆ ---   │
│ i16               ┆ u32   │
╞═══════════════════╪═══════╡
│ 15                ┆ 2     │
│ 5                 ┆ 4     │
│ 12                ┆ 2     │
│ 6                 ┆ 88    │
│ 1                 ┆ 506   │
│ …                 ┆ …     │
│ null              ┆ 26516 │
│ 7                 ┆ 2     │
│ 2                 ┆ 748   │
│ 9                 ┆ 2     │
│ 3                 ┆ 116   │
└───────────────────┴───────┘

shape: (2, 2)
┌───────────────┬───────┐
│ Free_Footwear ┆ count │
│ ---           ┆ ---   │
│ i16           ┆ u32   │
╞═══════════════╪═══════╡
│ null          ┆ 28140 │
│ 1             ┆ 70    │
└───────────────┴───────┘

shape: (3, 2)
┌───────────────────┬───────┐
│ Num_Free_Footwear ┆ count │
│ ---               ┆ ---   │
│ i16               ┆ u32   │
╞═══════════════════╪═══════╡
│ 1                 ┆ 48    │
│ 2                 ┆ 22    │
│ null              ┆ 28140 │
└───────────────────┴───────┘

shape: (2, 2)
┌────────────┬───────┐
│ Free_Other ┆ count │
│ ---        ┆ ---   │
│ i16        ┆ u32   │
╞════════════╪═══════╡
│ null       ┆ 27570 │
│ 1          ┆ 640   │
└────────────┴───────┘

shape: (26, 2)
┌────────────────┬───────┐
│ Num_Free_Other ┆ count │
│ ---            ┆ ---   │
│ i16            ┆ u32   │
╞════════════════╪═══════╡
│ 19             ┆ 8     │
│ 22             ┆ 2     │
│ 7              ┆ 32    │
│ 6              ┆ 80    │
│ 14             ┆ 18    │
│ …              ┆ …     │
│ 2              ┆ 30    │
│ 20             ┆ 4     │
│ 32             ┆ 2     │
│ 9              ┆ 30    │
│ 3              ┆ 16    │
└────────────────┴───────┘

# Filter Features

In [43]:
online_cols = [
'FSU_Serial_No',
'Online_Clothing',
'Online_Footwear',
]

free_cols = [
'Free_Clothing',
'Num_Free_Clothing',
]

possess_cols = [
'Possess_Television',
'Possess_Laptop',
'Possess_Mobile',
'Possess_Bicycle',
'Possess_Scooter',
'Possess_Car',
'Possess_Refrigerator',
'Possess_WashingMachine',
'Possess_AirCooler',
'TV_Facility_Type',
]

all_cols = (
    online_cols 
    + free_cols
    + possess_cols
)
pdf = pdf[all_cols]

display(f"Desire Filter shape {pdf.shape}")

'Desire Filter shape (28210, 15)'

In [44]:
def unique_values(cols: list[str]) -> None:
    for col in pdf[cols].columns:
        display(pdf[col].value_counts())

In [45]:
unique_values(cols=online_cols)

shape: (320, 2)
┌───────────────┬───────┐
│ FSU_Serial_No ┆ count │
│ ---           ┆ ---   │
│ i16           ┆ u32   │
╞═══════════════╪═══════╡
│ 25068         ┆ 36    │
│ 25096         ┆ 36    │
│ 25889         ┆ 36    │
│ 25218         ┆ 32    │
│ 25271         ┆ 36    │
│ …             ┆ …     │
│ 25005         ┆ 36    │
│ 25883         ┆ 36    │
│ 25098         ┆ 36    │
│ 25038         ┆ 36    │
│ 25048         ┆ 34    │
└───────────────┴───────┘

shape: (2, 2)
┌─────────────────┬───────┐
│ Online_Clothing ┆ count │
│ ---             ┆ ---   │
│ i16             ┆ u32   │
╞═════════════════╪═══════╡
│ 0               ┆ 23808 │
│ 1               ┆ 4402  │
└─────────────────┴───────┘

shape: (2, 2)
┌─────────────────┬───────┐
│ Online_Footwear ┆ count │
│ ---             ┆ ---   │
│ i16             ┆ u32   │
╞═════════════════╪═══════╡
│ 0               ┆ 25176 │
│ 1               ┆ 3034  │
└─────────────────┴───────┘

In [46]:
unique_values(cols=free_cols)

shape: (2, 2)
┌───────────────┬───────┐
│ Free_Clothing ┆ count │
│ ---           ┆ ---   │
│ i16           ┆ u32   │
╞═══════════════╪═══════╡
│ 1             ┆ 1694  │
│ null          ┆ 26516 │
└───────────────┴───────┘

shape: (13, 2)
┌───────────────────┬───────┐
│ Num_Free_Clothing ┆ count │
│ ---               ┆ ---   │
│ i16               ┆ u32   │
╞═══════════════════╪═══════╡
│ 1                 ┆ 506   │
│ 2                 ┆ 748   │
│ 7                 ┆ 2     │
│ 4                 ┆ 214   │
│ 10                ┆ 2     │
│ …                 ┆ …     │
│ 12                ┆ 2     │
│ 15                ┆ 2     │
│ 3                 ┆ 116   │
│ 8                 ┆ 8     │
│ null              ┆ 26516 │
└───────────────────┴───────┘

In [47]:
for col in ['Num_Free_Clothing', 'Free_Clothing']:
    pdf = pdf.with_columns(
    pl.col(col).fill_null(strategy='zero')
)

In [48]:
unique_values(cols=possess_cols)

shape: (2, 2)
┌────────────────────┬───────┐
│ Possess_Television ┆ count │
│ ---                ┆ ---   │
│ i16                ┆ u32   │
╞════════════════════╪═══════╡
│ null               ┆ 7438  │
│ 1                  ┆ 20772 │
└────────────────────┴───────┘

shape: (2, 2)
┌────────────────┬───────┐
│ Possess_Laptop ┆ count │
│ ---            ┆ ---   │
│ i16            ┆ u32   │
╞════════════════╪═══════╡
│ null           ┆ 26636 │
│ 1              ┆ 1574  │
└────────────────┴───────┘

shape: (2, 2)
┌────────────────┬───────┐
│ Possess_Mobile ┆ count │
│ ---            ┆ ---   │
│ i16            ┆ u32   │
╞════════════════╪═══════╡
│ 1              ┆ 27544 │
│ null           ┆ 666   │
└────────────────┴───────┘

shape: (2, 2)
┌─────────────────┬───────┐
│ Possess_Bicycle ┆ count │
│ ---             ┆ ---   │
│ i16             ┆ u32   │
╞═════════════════╪═══════╡
│ null            ┆ 16528 │
│ 1               ┆ 11682 │
└─────────────────┴───────┘

shape: (2, 2)
┌─────────────────┬───────┐
│ Possess_Scooter ┆ count │
│ ---             ┆ ---   │
│ i16             ┆ u32   │
╞═════════════════╪═══════╡
│ 1               ┆ 21326 │
│ null            ┆ 6884  │
└─────────────────┴───────┘

shape: (2, 2)
┌─────────────┬───────┐
│ Possess_Car ┆ count │
│ ---         ┆ ---   │
│ i16         ┆ u32   │
╞═════════════╪═══════╡
│ null        ┆ 26406 │
│ 1           ┆ 1804  │
└─────────────┴───────┘

shape: (2, 2)
┌──────────────────────┬───────┐
│ Possess_Refrigerator ┆ count │
│ ---                  ┆ ---   │
│ i16                  ┆ u32   │
╞══════════════════════╪═══════╡
│ null                 ┆ 18596 │
│ 1                    ┆ 9614  │
└──────────────────────┴───────┘

shape: (2, 2)
┌────────────────────────┬───────┐
│ Possess_WashingMachine ┆ count │
│ ---                    ┆ ---   │
│ i16                    ┆ u32   │
╞════════════════════════╪═══════╡
│ 1                      ┆ 4306  │
│ null                   ┆ 23904 │
└────────────────────────┴───────┘

shape: (2, 2)
┌───────────────────┬───────┐
│ Possess_AirCooler ┆ count │
│ ---               ┆ ---   │
│ i16               ┆ u32   │
╞═══════════════════╪═══════╡
│ null              ┆ 8426  │
│ 1                 ┆ 19784 │
└───────────────────┴───────┘

shape: (4, 2)
┌──────────────────┬───────┐
│ TV_Facility_Type ┆ count │
│ ---              ┆ ---   │
│ i16              ┆ u32   │
╞══════════════════╪═══════╡
│ 1                ┆ 1774  │
│ 2                ┆ 2252  │
│ 3                ┆ 16746 │
│ null             ┆ 7438  │
└──────────────────┴───────┘

In [49]:
pc = ['Possess_Television', 'Possess_Laptop', 'Possess_Mobile', 'Possess_Bicycle',
 'Possess_Scooter', 'Possess_Car', 'Possess_Refrigerator', 'Possess_WashingMachine',
 'Possess_AirCooler', 'Online_Clothing', 'Online_Footwear']

for col in pc:
        pdf = pdf.with_columns(
        pl.col(col).fill_null(strategy='zero')
)

In [50]:
pdf = pdf.with_columns(
        pl.col('TV_Facility_Type').fill_null(strategy='forward')
)

In [51]:
pdf.write_csv(r"C:\Users\Rudra\Desktop\rural-financial-inclusion-govt-scheme-recommendation\parquet-data\lev-11\data2\lev_11_mp_clean.csv")
pdf.write_parquet(r"C:\Users\Rudra\Desktop\rural-financial-inclusion-govt-scheme-recommendation\parquet-data\lev-11\data2\lev_11_mp_clean.parquet", compression="zstd")
print('Saved 🙌')

Saved 🙌