# Goal: statistical-summary

In [5]:
""" 
Goal: statistical-summary
Author: Rudra Prasad Bhuyan
Date: 10-10-2026 14:33 IST
"""

' \nGoal: statistical-summary\nAuthor: Rudra Prasad Bhuyan\nDate: 10-10-2026 14:33 IST\n'

In [6]:
import polars as pl

In [7]:
path = r"C:\Users\Rudra\Desktop\rural-financial-inclusion-govt-scheme-recommendation\parquet-data\lev-04\data\lev-04_merged.parquet"
pdf = pl.scan_parquet(path)

In [8]:
pdf.collect_schema()

Schema([('Survey_Name', String),
        ('Year', String),
        ('FSU_Serial_No', String),
        ('Sector', String),
        ('State', String),
        ('NSS_Region', String),
        ('District', String),
        ('Stratum', String),
        ('Sub_stratum', String),
        ('Panel', String),
        ('Sub_sample', String),
        ('FOD_Sub_Region', String),
        ('Sample_SU_No', String),
        ('Sample_Sub_Division_No', String),
        ('Second_Stage_Stratum_No', String),
        ('Sample_Household_No', String),
        ('Questionnaire_No', String),
        ('Level', String),
        ('Ration_Any_Item_Last_30_Days', String),
        ('Ration_Rice', String),
        ('Ration_Wheat', String),
        ('Ration_Coarse_Grain', String),
        ('Ration_Sugar', String),
        ('Ration_Pulses', String),
        ('Ration_Edible_Oil', String),
        ('Ration_Other_Food_Items', String),
        ('Online_Groceries', String),
        ('Online_Milk', String),
        ('Online_Vegetables', String),
        ('Online_Fresh_Fruits', String),
        ('Online_Dry_Fruits', String),
        ('Online_Egg_Fish_Meat', String),
        ('Online_Served_Processed_Food', String),
        ('Online_Packed_Processed_Food', String),
        ('Online_Other_Food_Items', String),
        ('Ceremony_Performed_Last_30_Days', String),
        ('Meals_Served_to_Non_HH_Members', String),
        ('Multiplier', Float64)])

# Useful Variables

In [9]:
lev_04_fin = ['Ration_Any_Item_Last_30_Days' ,'Ration_Rice',
              'Ration_Wheat','Ration_Coarse_Grain',
              'Ration_Sugar','Ration_Pulses',
              'Ration_Edible_Oil','Ration_Other_Food_Items']

lev_04_digital = [
    'Online_Groceries',
'Online_Milk',
'Online_Vegetables',
'Online_Fresh_Fruits',
'Online_Dry_Fruits',
'Online_Egg_Fish_Meat',
'Online_Served_Processed_Food',
'Online_Packed_Processed_Food',
'Online_Other_Food_Items',
]

lev_04_behavior = ['Ceremony_Performed_Last_30_Days']
lev_04_food = ['Meals_Served_to_Non_HH_Members']

lev_04_cols = (
    lev_04_food 
    + lev_04_behavior
    + lev_04_digital 
    + lev_04_fin
)

In [10]:
df = pdf.select(lev_04_cols)

In [11]:
df.head(2).collect()

shape: (2, 19)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Meals_Ser ┆ Ceremony_ ┆ Online_Gr ┆ Online_Mi ┆ … ┆ Ration_Su ┆ Ration_Pu ┆ Ration_Ed ┆ Ration_O │
│ ved_to_No ┆ Performed ┆ oceries   ┆ lk        ┆   ┆ gar       ┆ lses      ┆ ible_Oil  ┆ ther_Foo │
│ n_HH_Memb ┆ _Last_30_ ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ d_Items  │
│ ers       ┆ Day…      ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆ str       ┆ ---      │
│ ---       ┆ ---       ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
│ str       ┆ str       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 5         ┆ 2         ┆           ┆           ┆ … ┆           ┆           ┆           ┆          │
│ 5         ┆ 2         ┆           ┆           ┆ … ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [12]:
df = df.with_columns(
    [pl.col(col).cast(pl.Int32, strict=False) for col in lev_04_cols]
)

In [13]:
unique_counts = df.select(pl.all().n_unique()).collect()
unique_counts

shape: (1, 19)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Meals_Ser ┆ Ceremony_ ┆ Online_Gr ┆ Online_Mi ┆ … ┆ Ration_Su ┆ Ration_Pu ┆ Ration_Ed ┆ Ration_O │
│ ved_to_No ┆ Performed ┆ oceries   ┆ lk        ┆   ┆ gar       ┆ lses      ┆ ible_Oil  ┆ ther_Foo │
│ n_HH_Memb ┆ _Last_30_ ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ d_Items  │
│ ers       ┆ Day…      ┆ u32       ┆ u32       ┆   ┆ u32       ┆ u32       ┆ u32       ┆ ---      │
│ ---       ┆ ---       ┆           ┆           ┆   ┆           ┆           ┆           ┆ u32      │
│ u32       ┆ u32       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 163       ┆ 2         ┆ 2         ┆ 2         ┆ … ┆ 2         ┆ 2         ┆ 2         ┆ 2        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [14]:
unique_counts = df.select(pl.all().n_unique()).collect()

categorical_cols = []
numerical_cols = []

for col in df.columns:
    if unique_counts[col][0] <13:
        categorical_cols.append(col)
    else:
        numerical_cols.append(col)

C:\Users\Rudra\AppData\Local\Temp\ipykernel_10020\3703037397.py:6: PerformanceWarning: Determining the column names of a LazyFrame requires resolving its schema, which is a potentially expensive operation. Use `LazyFrame.collect_schema().names()` to get the column names without this warning.
  for col in df.columns:

In [15]:
stats = df.select(numerical_cols).describe()
with pl.Config(tbl_rows=-1, tbl_cols=-1):
    display(stats.to_pandas().T)

,0,1,2,3,4,5,6,7,8
statistic,count,null_count,mean,std,min,25%,50%,75%,max
Meals_Served_to_Non_HH_Members,785859.0,0.0,2.36058,12.320641,0.0,0.0,0.0,3.0,2000.0

In [16]:
for col in categorical_cols:
    print(col)
    counts = df.select(pl.col(col).value_counts(sort=True)).collect()
    
    with pl.Config(tbl_rows=-1, tbl_cols=-1):
        display(counts.unnest(col))

Ceremony_Performed_Last_30_Days

shape: (2, 2)
┌─────────────────────────────────┬────────┐
│ Ceremony_Performed_Last_30_Day… ┆ count  │
│ ---                             ┆ ---    │
│ i32                             ┆ u32    │
╞═════════════════════════════════╪════════╡
│ 2                               ┆ 775506 │
│ 1                               ┆ 10353  │
└─────────────────────────────────┴────────┘

Online_Groceries

shape: (2, 2)
┌──────────────────┬────────┐
│ Online_Groceries ┆ count  │
│ ---              ┆ ---    │
│ i32              ┆ u32    │
╞══════════════════╪════════╡
│ null             ┆ 749541 │
│ 1                ┆ 36318  │
└──────────────────┴────────┘

Online_Milk

shape: (2, 2)
┌─────────────┬────────┐
│ Online_Milk ┆ count  │
│ ---         ┆ ---    │
│ i32         ┆ u32    │
╞═════════════╪════════╡
│ null        ┆ 774054 │
│ 1           ┆ 11805  │
└─────────────┴────────┘

Online_Vegetables

shape: (2, 2)
┌───────────────────┬────────┐
│ Online_Vegetables ┆ count  │
│ ---               ┆ ---    │
│ i32               ┆ u32    │
╞═══════════════════╪════════╡
│ null              ┆ 774996 │
│ 1                 ┆ 10863  │
└───────────────────┴────────┘

Online_Fresh_Fruits

shape: (2, 2)
┌─────────────────────┬────────┐
│ Online_Fresh_Fruits ┆ count  │
│ ---                 ┆ ---    │
│ i32                 ┆ u32    │
╞═════════════════════╪════════╡
│ null                ┆ 777444 │
│ 1                   ┆ 8415   │
└─────────────────────┴────────┘

Online_Dry_Fruits

shape: (2, 2)
┌───────────────────┬────────┐
│ Online_Dry_Fruits ┆ count  │
│ ---               ┆ ---    │
│ i32               ┆ u32    │
╞═══════════════════╪════════╡
│ null              ┆ 780327 │
│ 1                 ┆ 5532   │
└───────────────────┴────────┘

Online_Egg_Fish_Meat

shape: (2, 2)
┌──────────────────────┬────────┐
│ Online_Egg_Fish_Meat ┆ count  │
│ ---                  ┆ ---    │
│ i32                  ┆ u32    │
╞══════════════════════╪════════╡
│ null                 ┆ 780225 │
│ 1                    ┆ 5634   │
└──────────────────────┴────────┘

Online_Served_Processed_Food

shape: (2, 2)
┌──────────────────────────────┬────────┐
│ Online_Served_Processed_Food ┆ count  │
│ ---                          ┆ ---    │
│ i32                          ┆ u32    │
╞══════════════════════════════╪════════╡
│ null                         ┆ 765234 │
│ 1                            ┆ 20625  │
└──────────────────────────────┴────────┘

Online_Packed_Processed_Food

shape: (2, 2)
┌──────────────────────────────┬────────┐
│ Online_Packed_Processed_Food ┆ count  │
│ ---                          ┆ ---    │
│ i32                          ┆ u32    │
╞══════════════════════════════╪════════╡
│ null                         ┆ 771186 │
│ 1                            ┆ 14673  │
└──────────────────────────────┴────────┘

Online_Other_Food_Items

shape: (2, 2)
┌─────────────────────────┬────────┐
│ Online_Other_Food_Items ┆ count  │
│ ---                     ┆ ---    │
│ i32                     ┆ u32    │
╞═════════════════════════╪════════╡
│ null                    ┆ 773637 │
│ 1                       ┆ 12222  │
└─────────────────────────┴────────┘

Ration_Any_Item_Last_30_Days

shape: (2, 2)
┌──────────────────────────────┬────────┐
│ Ration_Any_Item_Last_30_Days ┆ count  │
│ ---                          ┆ ---    │
│ i32                          ┆ u32    │
╞══════════════════════════════╪════════╡
│ 1                            ┆ 540498 │
│ 2                            ┆ 245361 │
└──────────────────────────────┴────────┘

Ration_Rice

shape: (2, 2)
┌─────────────┬────────┐
│ Ration_Rice ┆ count  │
│ ---         ┆ ---    │
│ i32         ┆ u32    │
╞═════════════╪════════╡
│ 1           ┆ 499827 │
│ null        ┆ 286032 │
└─────────────┴────────┘

Ration_Wheat

shape: (2, 2)
┌──────────────┬────────┐
│ Ration_Wheat ┆ count  │
│ ---          ┆ ---    │
│ i32          ┆ u32    │
╞══════════════╪════════╡
│ null         ┆ 491346 │
│ 1            ┆ 294513 │
└──────────────┴────────┘

Ration_Coarse_Grain

shape: (2, 2)
┌─────────────────────┬────────┐
│ Ration_Coarse_Grain ┆ count  │
│ ---                 ┆ ---    │
│ i32                 ┆ u32    │
╞═════════════════════╪════════╡
│ null                ┆ 768324 │
│ 1                   ┆ 17535  │
└─────────────────────┴────────┘

Ration_Sugar

shape: (2, 2)
┌──────────────┬────────┐
│ Ration_Sugar ┆ count  │
│ ---          ┆ ---    │
│ i32          ┆ u32    │
╞══════════════╪════════╡
│ null         ┆ 672075 │
│ 1            ┆ 113784 │
└──────────────┴────────┘

Ration_Pulses

shape: (2, 2)
┌───────────────┬────────┐
│ Ration_Pulses ┆ count  │
│ ---           ┆ ---    │
│ i32           ┆ u32    │
╞═══════════════╪════════╡
│ null          ┆ 717324 │
│ 1             ┆ 68535  │
└───────────────┴────────┘

Ration_Edible_Oil

shape: (2, 2)
┌───────────────────┬────────┐
│ Ration_Edible_Oil ┆ count  │
│ ---               ┆ ---    │
│ i32               ┆ u32    │
╞═══════════════════╪════════╡
│ null              ┆ 731328 │
│ 1                 ┆ 54531  │
└───────────────────┴────────┘

Ration_Other_Food_Items

shape: (2, 2)
┌─────────────────────────┬────────┐
│ Ration_Other_Food_Items ┆ count  │
│ ---                     ┆ ---    │
│ i32                     ┆ u32    │
╞═════════════════════════╪════════╡
│ null                    ┆ 727209 │
│ 1                       ┆ 58650  │
└─────────────────────────┴────────┘